version: '3.4'

services:
  datadb:
    image: mongo

  analyticsmongo:
    image: mongo


  hivemq:
    image: hivemq/hivemq4

  sensordevicemicroservice.api:
    image: ${DOCKER_REGISTRY-}sensordevicemicroserviceapi
    build:
      context: .
      dockerfile: SensorDeviceMicroservice/SensorDeviceMicroservice.API/Dockerfile

  datamicroservice.api:
    image: ${DOCKER_REGISTRY-}datamicroserviceapi
    build:
      context: .
      dockerfile: DataMicroservice/DataMicroservice.API/Dockerfile
  
  analyticsmicroservice.api:
    image: ${DOCKER_REGISTRY-}analyticsmicroserviceapi
    build:
      context: .
      dockerfile: AnalyticsMicroservice/AnalyticsMicroservice.API/Dockerfile

  commandmicroservice.api:
    image: ${DOCKER_REGISTRY-}commandmicroserviceapi
    build:
      context: .
      dockerfile: CommandMicroservice/CommandMicroservice.API/Dockerfile

volumes:
  mongo_data1:
  mongo_data2:
  


